### ISSUE TITLE
Dynamic website?

### ISSUE THREAD

**Issue by linonetwo** [cbroms/hyperfov-page-previews#1]
Hi, I'd like to use this technology in tiddlywiki, but it is a dynamic site, that new things will add to the page.

I tried call \`window._setPagePreviews\`_ multiple times, but it doesn't work. Can you make it recognize newly appeared `a` when call setPagePreviews again?

**Comment by cbroms** [comment]
Hey, I've rewritten this package a bit since this issue was opened; this should be addressed. You can individually instantiate each element with `linkPreview(elt)` and any updates to the referenced element are reflected in the preview. Any new elements can be instantiated whenever. You can find a react example [here](https://github.com/cbroms/link-previews/tree/master/examples).
